function cent_est = cent_estimate(ty, tz, p)
% @param t_hori the horizontal t value 
% @param t_vert the vertical t value 
% @param p the matrix containing slopes and intercepts generated by
% get_centroid_estimate()
% @version 5.1.2018
% gets the list of predicted centroids
cent_est_y = glmval(p.by,ty,'identity');
cent_est_z = glmval(p.bz,tz,'identity');
cent_est = horzcat(cent_est_y, cent_est_z);
end
